### ISSUE TITLE
One instruction missing on installing-sudokuhax

### ISSUE THREAD

**Issue by fatburd** [emiyl/dsi.cfw.guide#1]
On section **Launching twlnf**, instructions go like this:

7. Select Copy > Back > Exit
8. Click on the Flipnote frog icon in the bottom left
9. Click on the film roll icon.

I _think_ that between 7 and 8, there should be instructions telling that you need to select the second note. I tried doing it on the first note for a long time and got myself on a "instructions unclear, dick stuck on sd card" moment.

**Comment by Robz8** [comment]
Step is now added!
