### ISSUE TITLE
Missing steps at Installing TwiLight Menu ++ Page

### ISSUE THREAD

**Issue by John256145** [emiyl/dsi.cfw.guide#16]
Hello, I noticed that there are two missing steps that are worth adding to the guide. At the [Installing TwiLight Menu ++](https://dsi.cfw.guide/installing-twilight-menu++.html) page, I would recommend adding these steps:

Between steps 4 and 5, instruct the user to eject their sd card and insert it to their system. I know this is a bit nitpicky, but it will remain consistent with the rest of the guide.

In step 5, instruct the user to load Unlaunch (by holding the A button before powering on) and navigating to the Options menu in order to change the No_Button configuration from Hiya CFW to TwilightMenu++. 

Thanks so much for the guide by the way, it was very useful!

**Comment by NightYoshi370** [comment]
This is now invalid, with the way I've changed the other pages. Please close
