### ISSUE TITLE
hiya cfw helper

### ISSUE THREAD

**Issue by thomleg50** [emiyl/dsi.cfw.guide#2]
hi,
when i use hiya cfw helper it say im not in the good directory but im in 
can you help me ?
Thanks

**Comment by jerbear64** [comment]
User error, as discussed on Discord (yes, we know that's your alt.)

**Comment by jerbear64** [comment]
I'll add that I do have plans to compile the Python scripts into standalone executables very soon, though, which will eliminate much of the user error in installing Python.

**Comment by jerbear64** [comment]
Standalone EXE's available as of 67562d9.

**Comment by thomleg50** [comment]
it require no$gba footer how ?

**Comment by jerbear64** [comment]
I need a full screenshot of the script's output. Considering the previous user error it may be that you somehow removed TWLTool from the directory, or just renamed yet another directory to "for PC" to trick the self-check.

**Comment by thomleg50** [comment]
![image](https://user-images.githubusercontent.com/26003687/41794634-dcc55aaa-7657-11e8-9869-ba9fff302a3c.png)

It's here ! 
please fix it please ?

**Comment by jerbear64** [comment]
You somehow dropped the `.exe` from `twltool`, rename `twltool` to `twltool.exe`

**Comment by thomleg50** [comment]
thanks it's fixed now but on boot after hiya splash it display a white screen can you help me ?
