### ISSUE TITLE
Remove fuse-3ds (and WinSfp) requirement(s)

### ISSUE THREAD

**Issue by mondul** [emiyl/dsi.cfw.guide#4]
On the "Installing HiyaCFW" page, at the SDNAND Creation section, fuse-3ds is not required because hiyacfw_helper creates a nand_dec.bin file that can be directly mounted with OSFMount, which will show some partitions to choose, and choosing the big one will give access to the files in twl_main.img.

On linux, the file can be read by creating loop devices from it with kpartx and mounting them with mount.

On macOS I did it by attaching it as a raw disk image using hdiutil and then mounting it with diskutil.

**Comment by jerbear64** [comment]
Closed in 24e12e7, thank you for the helper GUI.
