### ISSUE TITLE
Needs update for FailZone

### ISSUE THREAD

**Issue by SoulRepo** [emiyl/dsi.cfw.guide#6]
FailZone has been published today, and is available on the DSi Homebrew discord. Can we have an update?

**Comment by jerbear64** [comment]
It was published *as a private demo* today. No new testers are being added, and there are only a few. Saying it's "available" isn't exactly true.

FailZone is also exponentially more difficult to set up than Flipnote Lenny. In the future, when FailZone is publicly released and more ironed out, it will be added. For now, not only is FailZone in an unreleased private demo state, but is also unfinished.
