### ISSUE TITLE
Mounting Decrypted NAND ERROR

### ISSUE THREAD

**Issue by yuu002** [emiyl/dsi.cfw.guide#9]
The problem are

when i used NAND in HiyaCFW Helper and that show error 

"Mounting Decrypted NAND....
ERROR : Mounter Failed"

I've tried reformat my SD Card and Reinstalling HiyaCFW, But it's still the same.
I just following the guide on Dsi Guide btw

Help me
Note: I used 32GB SD Card and full formatted fat32. I've install Twilight menu ++ to but i can't play DS Rom, it'll be freezes and keep white screen after loading screen.  
Thanks

**Comment by emiyl** [comment]
Please ask on either the [NDS(i)Brew Scene](https://discord.gg/XRXjzY5) or [Nintendo Homebrew](https://discord.gg/C29hYvh) Discord servers.
